config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root "dashboard#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.client?
      can :manage, Product, user_id: user.id
    elsif user.admin?
      can :manage
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products, dependent: :destroy

  def admin?
    has_role?(:admin)
  end

  def client?
    has_role?(:client)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boostrap_class(alert)
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
      danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
        concat(content_tag(:button, id: "close-button", class: "close", type: :button, data: { dismiss: 'alert' }, "aria-label" => :Close) do
          concat content_tag(:span, "&times;".html_safe, "aria-hidden" => true)
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/index.html.erb
<%= flash_messages %>
<div class="block">
  <header class="header-group">
    <h2>Welcome to Rails Authentication, Authorization by Damian Mamla.</h2>
  </header>
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="/">Rails Tutorial</a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", products_path %></li>
                <li><%= link_to "New", new_product_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                  <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
                <% if user_signed_in? %>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit 'Create', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h2>Editing Product</h2>

<%= render 'form' %>

<%= link_to 'Show', @product, class: "btn btn-warning" %>
<%= link_to 'Back', products_path, class: "btn btn-default" %>

app/views/products/index.html.erb
<%= flash_messages %>
<h2>Products List</h2>
<div class="product-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-2">Name</th>
        <th class="col-md-2">Price</th>
        <th class="col-md-2">Creator</th>
        <th class="col-md-4">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td class="col-md-2"><%= product.name %></td>
          <td class="col-md-2">$<%= product.price %></td>
          <td class="col-md-2"><%= product.user.try(:email) %></td>
          <td class="col-md-4">
            <%= link_to 'Show', product_path(product), class: "btn btn-info" %>
            <%= link_to 'Edit', edit_product_path(product), class: "btn  btn-warning" %>
            <%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>

app/views/products/new.html.erb
<h2>New Product</h2>

<%= render 'form' %>

<%= link_to "Back", products_path, class: "btn btn-default" %>

app/views/products/show.html.erb
<%= flash_messages %>
<h2>Product</h2>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
    $<%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-warning" %>
<%= link_to "Back", products_path, class: "btn btn-default" %>